theme = "ananke"

baseURL = "https://mukai-hic.github.io/ai-note"
languageCode = "ja-jp"
title = "AI-note"

[params]
  description = "AI-note"
  
[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 2
